name: linux

on:
  push:
    branches: [ mob ]
  pull_request:
    branches: [ mob ]

jobs:
  build-linux:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04]
        cc: [clang, gcc]

    steps:
    - uses: actions/checkout@v2

    - name: configure
      run: ./configure --cc=${{ matrix.cc }}

    - name: make
      run: make

    - name: make test
      run: test ${{ matrix.cc }} != "gcc" || make test
