name: macos

on:
  push:
    branches: [ mob ]
  pull_request:
    branches: [ mob ]

jobs:
  build-macos:
    runs-on: macos-latest

    strategy:
      matrix:
        cc: [clang, gcc]

    steps:
    - uses: actions/checkout@v2

    - name: configure
      run: ./configure --cc=${{ matrix.cc }}

    - name: make
      run: |
        echo | gcc -E -Wp,-v -
        make
