name: linux

on:
  push:
    branches: [ mob ]
  pull_request:
    branches: [ mob ]

jobs:
  build-macos:
    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2

    - name: install
      run: sudo xcode-select -switch /Applications/Xcode_11.15.app

    - name: configure
      run: ./configure --cc=clang

    - name: make
      run: make

    - name: make test
      run: make test
