name: windows

on:
  push:
    branches: [ mob ]
  pull_request:
    branches: [ mob ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: make
      run: |
        Push-Location win32
        .\vsenv.ps1
        .\build-tcc.bat -c cl.exe
